### ISSUE TITLE
Emit webpack config errors

### ISSUE THREAD

**Issue by nathanbowser** [axisdefined/metalpress#20]
If you pass in a webpack.config file and there is an error, the error is swallowed and your webpack config file isn't used, and you don't know there is an error.

The error is swallowed here: https://github.com/axisdefined/metalpress/blob/master/src/config/configure-webpack.js#L39

**Comment by cameronroe** [comment]
In this context the try/catch is just trying to load the project webpack configs. In the standard case that a project doesn't need to override them, they wouldn't need to see an error for that. If it's easier, I can rip out the resolve property, but then you'd need to override that in your config.

If you'd rather see a log for what's going on with the configs, I can log it out for verbosity but didn't think that would be desirable.

**Comment by nathanbowser** [comment]
I don't care how you solve it, but if you provide someone with the ability so send in a webpack config, and it throws errors, the end user needs to know.

**Comment by cameronroe** [comment]
https://github.com/axisdefined/metalpress/pull/22
