### ISSUE TITLE
Cleanup dependencies

### ISSUE THREAD

**Issue by nathanbowser** [axisdefined/metalpress#21]
I'm wondering if the listed dependencies is accurate. For a simple static webpage that depends on this project, it takes awhile for a fresh install because of all dependencies:

```
$ time npm i
...

real	5m51.668s
user	1m8.121s
sys	0m22.777s
```

This is also somewhat alarming (but I guess not too surprising because of how npm works):

```
$ ls -aslh node_modules/ | wc -l
1075
```

**Comment by cameronroe** [comment]
Metalpress does not include a cli. That might be making it bigger than expected. If it's a big issue, I can look into separating that out to a new package. I'll most likely be doing this in the future anyway as the project is likely grow in features.

**Comment by cameronroe** [comment]
Should be faster now! 🚀

```
$ time npm install metalpress --save

real	1m52.110s
user	0m52.002s
sys	0m10.579s
```

**Comment by nathanbowser** [comment]
Much better. Thank you.

**Comment by cameronroe** [comment]
Also, the cli is now [here](https://github.com/axisdefined/metalpress-cli)
